# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.failure_response import FailureResponse

class TestFailureResponse(unittest.TestCase):
    """FailureResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FailureResponse:
        """Test FailureResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FailureResponse`
        """
        model = FailureResponse()
        if include_optional:
            return FailureResponse(
                id = '',
                run_id = '',
                account_id = '',
                account_url = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                url = '',
                handler_name = '',
                message = ''
            )
        else:
            return FailureResponse(
                id = '',
                run_id = '',
                account_id = '',
                account_url = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                url = '',
                handler_name = '',
                message = '',
        )
        """

    def testFailureResponse(self):
        """Test FailureResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
