# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.resources_skill_md import ResourcesSkillMd

class TestResourcesSkillMd(unittest.TestCase):
    """ResourcesSkillMd unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourcesSkillMd:
        """Test ResourcesSkillMd
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourcesSkillMd`
        """
        model = ResourcesSkillMd()
        if include_optional:
            return ResourcesSkillMd(
                status = 'found',
                reason = 'blocked'
            )
        else:
            return ResourcesSkillMd(
                status = 'found',
        )
        """

    def testResourcesSkillMd(self):
        """Test ResourcesSkillMd"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
