# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.proxy_mode import ProxyMode

class TestProxyMode(unittest.TestCase):
    """ProxyMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProxyMode(self):
        """Test ProxyMode"""
        # inst = ProxyMode()

if __name__ == '__main__':
    unittest.main()
