# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.smart_content_project import SmartContentProject

class TestSmartContentProject(unittest.TestCase):
    """SmartContentProject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SmartContentProject:
        """Test SmartContentProject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SmartContentProject`
        """
        model = SmartContentProject()
        if include_optional:
            return SmartContentProject(
                account_id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = 56,
                model_id = 1,
                name = '',
                quantity = 'single'
            )
        else:
            return SmartContentProject(
                account_id = 56,
        )
        """

    def testSmartContentProject(self):
        """Test SmartContentProject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
