# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.crawl_job_input import CrawlJobInput

class TestCrawlJobInput(unittest.TestCase):
    """CrawlJobInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CrawlJobInput:
        """Test CrawlJobInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CrawlJobInput`
        """
        model = CrawlJobInput()
        if include_optional:
            return CrawlJobInput(
                website_url = '0',
                sitemaps = [
                    '0'
                    ],
                max_concurrent_requests = 56,
                max_pages = 56,
                request_timeout_ms = 56,
                render_timeout_ms = 56,
                request_handler_timeout_ms = 56,
                max_retries = 56,
                respect_robots = True,
                crawl_delay_override = 1.337,
                js_render_mode = 'never',
                discovery_sources = 'sitemap-only',
                render_wait_until = 'domcontentloaded',
                render_wait_for_selector = '',
                render_wait_for_timeout_ms = 56,
                render_wait_for_js = '',
                render_max_total_wait_ms = 56
            )
        else:
            return CrawlJobInput(
                website_url = '0',
                sitemaps = [
                    '0'
                    ],
        )
        """

    def testCrawlJobInput(self):
        """Test CrawlJobInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
