# coding: utf-8

"""
    Analysis

    Analyse content using Linked Data and Knowledge Graphs.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift-client.models.response import Response

class TestResponse(unittest.TestCase):
    """Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Response:
        """Test Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Response`
        """
        model = Response()
        if include_optional:
            return Response(
                entities = {
                    'key' : wordlift-client.models.entity.Entity(
                        entity_id = '', 
                        confidence = 1.337, 
                        main_type = '', 
                        types = [
                            ''
                            ], 
                        label = '', 
                        description = '', 
                        images = [
                            ''
                            ], 
                        same_as = [
                            ''
                            ], 
                        properties = wordlift-client.models.properties.Properties(
                            latitude = 1.337, 
                            longitude = 1.337, ), 
                        synonyms = [
                            ''
                            ], )
                    },
                annotations = {
                    'key' : wordlift-client.models.annotation.Annotation(
                        annotation_id = '', 
                        start = 56, 
                        end = 56, 
                        text = '', 
                        entity_matches = [
                            wordlift-client.models.entity_match.EntityMatch(
                                confidence = 1.337, 
                                entity_id = '', )
                            ], )
                    },
                images = [
                    wordlift-client.models.image.Image(
                        label = '', 
                        url = '', )
                    ],
                languages = [
                    ''
                    ],
                topics = [
                    wordlift-client.models.topic.Topic(
                        label = '', 
                        description = '', 
                        uri = '', 
                        confidence = 1.337, 
                        images = [
                            ''
                            ], 
                        same_as = [
                            ''
                            ], )
                    ],
                content = ''
            )
        else:
            return Response(
        )
        """

    def testResponse(self):
        """Test Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
