# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.items_inner import ItemsInner

class TestItemsInner(unittest.TestCase):
    """ItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemsInner:
        """Test ItemsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemsInner`
        """
        model = ItemsInner()
        if include_optional:
            return ItemsInner(
                id = '',
                severity = 'required',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                type = 'structured_data',
                config = wordlift_client.models.structured_data_expectation_config.StructuredDataExpectationConfig(
                    entity_type = '0', 
                    property_path = '0', 
                    constraint = 'present', )
            )
        else:
            return ItemsInner(
                id = '',
                severity = 'required',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                type = 'structured_data',
                config = wordlift_client.models.structured_data_expectation_config.StructuredDataExpectationConfig(
                    entity_type = '0', 
                    property_path = '0', 
                    constraint = 'present', ),
        )
        """

    def testItemsInner(self):
        """Test ItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
