# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.o_auth2_connector_authorization_response import OAuth2ConnectorAuthorizationResponse

class TestOAuth2ConnectorAuthorizationResponse(unittest.TestCase):
    """OAuth2ConnectorAuthorizationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OAuth2ConnectorAuthorizationResponse:
        """Test OAuth2ConnectorAuthorizationResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OAuth2ConnectorAuthorizationResponse`
        """
        model = OAuth2ConnectorAuthorizationResponse()
        if include_optional:
            return OAuth2ConnectorAuthorizationResponse(
                access_token_issued_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                account_id = 56,
                connector_id = '',
                refresh_token_issued_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = ''
            )
        else:
            return OAuth2ConnectorAuthorizationResponse(
        )
        """

    def testOAuth2ConnectorAuthorizationResponse(self):
        """Test OAuth2ConnectorAuthorizationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
