# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.graph_kpi_http_validation_error import GraphKpiHTTPValidationError

class TestGraphKpiHTTPValidationError(unittest.TestCase):
    """GraphKpiHTTPValidationError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GraphKpiHTTPValidationError:
        """Test GraphKpiHTTPValidationError
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GraphKpiHTTPValidationError`
        """
        model = GraphKpiHTTPValidationError()
        if include_optional:
            return GraphKpiHTTPValidationError(
                detail = [
                    wordlift_client.models.validation_error.ValidationError(
                        loc = [
                            null
                            ], 
                        msg = '', 
                        type = '', 
                        input = null, 
                        ctx = wordlift_client.models.context.Context(), )
                    ]
            )
        else:
            return GraphKpiHTTPValidationError(
        )
        """

    def testGraphKpiHTTPValidationError(self):
        """Test GraphKpiHTTPValidationError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
