# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.list_expectation_severity_response import ListExpectationSeverityResponse

class TestListExpectationSeverityResponse(unittest.TestCase):
    """ListExpectationSeverityResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListExpectationSeverityResponse:
        """Test ListExpectationSeverityResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListExpectationSeverityResponse`
        """
        model = ListExpectationSeverityResponse()
        if include_optional:
            return ListExpectationSeverityResponse(
                items = [
                    wordlift_client.models.expectation_severity_response.ExpectationSeverityResponse(
                        expectation_id = '', 
                        severity = 'required', )
                    ],
                total = 56,
                next_cursor = ''
            )
        else:
            return ListExpectationSeverityResponse(
                items = [
                    wordlift_client.models.expectation_severity_response.ExpectationSeverityResponse(
                        expectation_id = '', 
                        severity = 'required', )
                    ],
                total = 56,
        )
        """

    def testListExpectationSeverityResponse(self):
        """Test ListExpectationSeverityResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
