# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.well_known_files import WellKnownFiles

class TestWellKnownFiles(unittest.TestCase):
    """WellKnownFiles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WellKnownFiles:
        """Test WellKnownFiles
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WellKnownFiles`
        """
        model = WellKnownFiles()
        if include_optional:
            return WellKnownFiles(
                ai_plugin = True,
                ucp = True,
                security = True,
                asset_links = True,
                apple_association = True,
                llms_txt = True
            )
        else:
            return WellKnownFiles(
        )
        """

    def testWellKnownFiles(self):
        """Test WellKnownFiles"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
