# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.api.account_o_auth2_connectors_api import AccountOAuth2ConnectorsApi


class TestAccountOAuth2ConnectorsApi(unittest.TestCase):
    """AccountOAuth2ConnectorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountOAuth2ConnectorsApi()

    def tearDown(self) -> None:
        pass

    def test_authorization(self) -> None:
        """Test case for authorization

        Get account connector authorization
        """
        pass

    def test_create_authorization_request(self) -> None:
        """Test case for create_authorization_request

        Create account connector authorization request
        """
        pass

    def test_delete_authorization(self) -> None:
        """Test case for delete_authorization

        Disconnect account connector authorization
        """
        pass


if __name__ == '__main__':
    unittest.main()
