# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.reset_account_request import ResetAccountRequest

class TestResetAccountRequest(unittest.TestCase):
    """ResetAccountRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResetAccountRequest:
        """Test ResetAccountRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResetAccountRequest`
        """
        model = ResetAccountRequest()
        if include_optional:
            return ResetAccountRequest(
                keep_country = True,
                keep_language = True,
                keep_url = True
            )
        else:
            return ResetAccountRequest(
        )
        """

    def testResetAccountRequest(self):
        """Test ResetAccountRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
