# coding: utf-8

"""
    Analysis

    Analyse content using Linked Data and Knowledge Graphs.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.api.seo_scores_api import SEOScoresApi


class TestSEOScoresApi(unittest.TestCase):
    """SEOScoresApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SEOScoresApi()

    def tearDown(self) -> None:
        pass

    def test_create_seo_score(self) -> None:
        """Test case for create_seo_score

        Create
        """
        pass


if __name__ == '__main__':
    unittest.main()
