# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.api.segment_globs_api import SegmentGlobsApi


class TestSegmentGlobsApi(unittest.TestCase):
    """SegmentGlobsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SegmentGlobsApi()

    def tearDown(self) -> None:
        pass

    def test_add_segment_glob_accounts_account_id_monitoring_segments_segment_id_globs_post(self) -> None:
        """Test case for add_segment_glob_accounts_account_id_monitoring_segments_segment_id_globs_post

        Add Segment Glob
        """
        pass

    def test_delete_segment_glob_accounts_account_id_monitoring_segments_segment_id_globs_glob_id_delete(self) -> None:
        """Test case for delete_segment_glob_accounts_account_id_monitoring_segments_segment_id_globs_glob_id_delete

        Delete Segment Glob
        """
        pass

    def test_list_segment_globs_accounts_account_id_monitoring_segments_segment_id_globs_get(self) -> None:
        """Test case for list_segment_globs_accounts_account_id_monitoring_segments_segment_id_globs_get

        List Segment Globs
        """
        pass

    def test_replace_segment_globs_accounts_account_id_monitoring_segments_segment_id_globs_put(self) -> None:
        """Test case for replace_segment_globs_accounts_account_id_monitoring_segments_segment_id_globs_put

        Replace Segment Globs
        """
        pass


if __name__ == '__main__':
    unittest.main()
