# coding: utf-8

"""
    Analysis

    Analyse content using Linked Data and Knowledge Graphs.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.api.entity_gaps_api import EntityGapsApi


class TestEntityGapsApi(unittest.TestCase):
    """EntityGapsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EntityGapsApi()

    def tearDown(self) -> None:
        pass

    def test_create_entity_gap(self) -> None:
        """Test case for create_entity_gap

        Create
        """
        pass


if __name__ == '__main__':
    unittest.main()
