# coding: utf-8

"""
    Analysis

    Analyse content using Linked Data and Knowledge Graphs.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.exchange_auth_code_response import ExchangeAuthCodeResponse

class TestExchangeAuthCodeResponse(unittest.TestCase):
    """ExchangeAuthCodeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExchangeAuthCodeResponse:
        """Test ExchangeAuthCodeResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExchangeAuthCodeResponse`
        """
        model = ExchangeAuthCodeResponse()
        if include_optional:
            return ExchangeAuthCodeResponse(
                access_token = '',
                expires_in = 56,
                refresh_token = '',
                scope = '',
                token_type = ''
            )
        else:
            return ExchangeAuthCodeResponse(
        )
        """

    def testExchangeAuthCodeResponse(self):
        """Test ExchangeAuthCodeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
