# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.segment_summary_item import SegmentSummaryItem

class TestSegmentSummaryItem(unittest.TestCase):
    """SegmentSummaryItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SegmentSummaryItem:
        """Test SegmentSummaryItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SegmentSummaryItem`
        """
        model = SegmentSummaryItem()
        if include_optional:
            return SegmentSummaryItem(
                segment_id = '',
                monitor_count = 56,
                expectation_count = 56
            )
        else:
            return SegmentSummaryItem(
                segment_id = '',
                monitor_count = 56,
                expectation_count = 56,
        )
        """

    def testSegmentSummaryItem(self):
        """Test SegmentSummaryItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
