# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.website_page_list_response import WebsitePageListResponse

class TestWebsitePageListResponse(unittest.TestCase):
    """WebsitePageListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebsitePageListResponse:
        """Test WebsitePageListResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebsitePageListResponse`
        """
        model = WebsitePageListResponse()
        if include_optional:
            return WebsitePageListResponse(
                items = [
                    wordlift_client.models.website_page_summary.WebsitePageSummary(
                        page_id = 56, 
                        host = '', 
                        run_id = '', 
                        last_crawled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = 'ok', 
                        url_requested = '', 
                        url_final = '', 
                        canonical_url = '', 
                        status_code = 56, )
                    ],
                page = wordlift_client.models.pagination_info.PaginationInfo(
                    offset = 56, 
                    limit = 56, 
                    total = 56, 
                    next_cursor = 56, )
            )
        else:
            return WebsitePageListResponse(
                items = [
                    wordlift_client.models.website_page_summary.WebsitePageSummary(
                        page_id = 56, 
                        host = '', 
                        run_id = '', 
                        last_crawled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = 'ok', 
                        url_requested = '', 
                        url_final = '', 
                        canonical_url = '', 
                        status_code = 56, )
                    ],
                page = wordlift_client.models.pagination_info.PaginationInfo(
                    offset = 56, 
                    limit = 56, 
                    total = 56, 
                    next_cursor = 56, ),
        )
        """

    def testWebsitePageListResponse(self):
        """Test WebsitePageListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
