# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.monitor_health_response import MonitorHealthResponse

class TestMonitorHealthResponse(unittest.TestCase):
    """MonitorHealthResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonitorHealthResponse:
        """Test MonitorHealthResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MonitorHealthResponse`
        """
        model = MonitorHealthResponse()
        if include_optional:
            return MonitorHealthResponse(
                status = ''
            )
        else:
            return MonitorHealthResponse(
                status = '',
        )
        """

    def testMonitorHealthResponse(self):
        """Test MonitorHealthResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
