# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.api.audit_api import AuditApi


class TestAuditApi(unittest.TestCase):
    """AuditApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuditApi()

    def tearDown(self) -> None:
        pass

    def test_audit_website(self) -> None:
        """Test case for audit_website

        Website Audit
        """
        pass


if __name__ == '__main__':
    unittest.main()
