# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.page_info import PageInfo

class TestPageInfo(unittest.TestCase):
    """PageInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageInfo:
        """Test PageInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageInfo`
        """
        model = PageInfo()
        if include_optional:
            return PageInfo(
                limit = 56,
                cursor = ''
            )
        else:
            return PageInfo(
                limit = 56,
        )
        """

    def testPageInfo(self):
        """Test PageInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
