# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.validation_error1_detail_inner import ValidationError1DetailInner

class TestValidationError1DetailInner(unittest.TestCase):
    """ValidationError1DetailInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationError1DetailInner:
        """Test ValidationError1DetailInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationError1DetailInner`
        """
        model = ValidationError1DetailInner()
        if include_optional:
            return ValidationError1DetailInner(
                loc = [
                    ''
                    ],
                msg = '',
                type = ''
            )
        else:
            return ValidationError1DetailInner(
        )
        """

    def testValidationError1DetailInner(self):
        """Test ValidationError1DetailInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
