# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.crawl_job_response import CrawlJobResponse

class TestCrawlJobResponse(unittest.TestCase):
    """CrawlJobResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CrawlJobResponse:
        """Test CrawlJobResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CrawlJobResponse`
        """
        model = CrawlJobResponse()
        if include_optional:
            return CrawlJobResponse(
                id = '',
                run_id = '',
                status = 'queued',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                input = {"discovery_sources":"sitemap-only","js_render_mode":"auto","max_pages":10000,"max_retries":2,"respect_robots":true,"sitemaps":["https://www.example.org/sitemap.xml"],"website_url":"https://www.example.org/"},
                pages_total = 56,
                pages_with_error = 56,
                error_message = ''
            )
        else:
            return CrawlJobResponse(
                id = '',
                run_id = '',
                status = 'queued',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                input = {"discovery_sources":"sitemap-only","js_render_mode":"auto","max_pages":10000,"max_retries":2,"respect_robots":true,"sitemaps":["https://www.example.org/sitemap.xml"],"website_url":"https://www.example.org/"},
        )
        """

    def testCrawlJobResponse(self):
        """Test CrawlJobResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
