# coding: utf-8

"""
    Analysis

    Analyse content using Linked Data and Knowledge Graphs.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.api.botify_crawl_imports_api import BotifyCrawlImportsApi


class TestBotifyCrawlImportsApi(unittest.TestCase):
    """BotifyCrawlImportsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BotifyCrawlImportsApi()

    def tearDown(self) -> None:
        pass

    def test_create_botify_crawl_import(self) -> None:
        """Test case for create_botify_crawl_import

        Create
        """
        pass


if __name__ == '__main__':
    unittest.main()
