# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.list_expectation_summary_by_type_response import ListExpectationSummaryByTypeResponse

class TestListExpectationSummaryByTypeResponse(unittest.TestCase):
    """ListExpectationSummaryByTypeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListExpectationSummaryByTypeResponse:
        """Test ListExpectationSummaryByTypeResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListExpectationSummaryByTypeResponse`
        """
        model = ListExpectationSummaryByTypeResponse()
        if include_optional:
            return ListExpectationSummaryByTypeResponse(
                items = [
                    wordlift_client.models.expectation_summary_by_type_item.ExpectationSummaryByTypeItem(
                        segment_id = '', 
                        expectation_type = 'structured_data', 
                        monitor_count = 56, 
                        expectation_count = 56, 
                        stats = [
                            wordlift_client.models.expectation_summary_type_stat.ExpectationSummaryTypeStat(
                                severity = 'required', 
                                outcome = 'pass', 
                                monitor_count = 56, 
                                expectation_count = 56, 
                                expectation_evaluation_count = 56, )
                            ], )
                    ],
                total = 56,
                next_cursor = ''
            )
        else:
            return ListExpectationSummaryByTypeResponse(
                items = [
                    wordlift_client.models.expectation_summary_by_type_item.ExpectationSummaryByTypeItem(
                        segment_id = '', 
                        expectation_type = 'structured_data', 
                        monitor_count = 56, 
                        expectation_count = 56, 
                        stats = [
                            wordlift_client.models.expectation_summary_type_stat.ExpectationSummaryTypeStat(
                                severity = 'required', 
                                outcome = 'pass', 
                                monitor_count = 56, 
                                expectation_count = 56, 
                                expectation_evaluation_count = 56, )
                            ], )
                    ],
                total = 56,
        )
        """

    def testListExpectationSummaryByTypeResponse(self):
        """Test ListExpectationSummaryByTypeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
