# coding: utf-8

"""
    Analysis

    Analyse content using Linked Data and Knowledge Graphs.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.api.content_generation_renders_api import ContentGenerationRendersApi


class TestContentGenerationRendersApi(unittest.TestCase):
    """ContentGenerationRendersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContentGenerationRendersApi()

    def tearDown(self) -> None:
        pass

    def test_render_template(self) -> None:
        """Test case for render_template

        Render
        """
        pass

    def test_render_template_collection(self) -> None:
        """Test case for render_template_collection

        Render
        """
        pass


if __name__ == '__main__':
    unittest.main()
