# coding: utf-8

"""
    Analysis

    Analyse content using Linked Data and Knowledge Graphs.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.page_vector_search_question_response_item import PageVectorSearchQuestionResponseItem

class TestPageVectorSearchQuestionResponseItem(unittest.TestCase):
    """PageVectorSearchQuestionResponseItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageVectorSearchQuestionResponseItem:
        """Test PageVectorSearchQuestionResponseItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageVectorSearchQuestionResponseItem`
        """
        model = PageVectorSearchQuestionResponseItem()
        if include_optional:
            return PageVectorSearchQuestionResponseItem(
                first = '',
                items = [
                    wordlift_client.models.vector_search_question_response_item.VectorSearchQuestionResponseItem(
                        answer = '', 
                        question = '', )
                    ],
                last = '',
                next = '',
                prev = '',
                var_self = ''
            )
        else:
            return PageVectorSearchQuestionResponseItem(
                first = '',
                items = [
                    wordlift_client.models.vector_search_question_response_item.VectorSearchQuestionResponseItem(
                        answer = '', 
                        question = '', )
                    ],
                last = '',
                next = '',
                prev = '',
                var_self = '',
        )
        """

    def testPageVectorSearchQuestionResponseItem(self):
        """Test PageVectorSearchQuestionResponseItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
