# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.monitor_run_response import MonitorRunResponse

class TestMonitorRunResponse(unittest.TestCase):
    """MonitorRunResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonitorRunResponse:
        """Test MonitorRunResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MonitorRunResponse`
        """
        model = MonitorRunResponse()
        if include_optional:
            return MonitorRunResponse(
                id = '',
                status = 'dispatching',
                dispatched_pages = 56,
                fetched_pages = 56,
                failed_fetches = 56,
                checked_pages = 56,
                end_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_progress_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return MonitorRunResponse(
                id = '',
                status = 'dispatching',
                dispatched_pages = 56,
                fetched_pages = 56,
                failed_fetches = 56,
                checked_pages = 56,
                last_progress_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testMonitorRunResponse(self):
        """Test MonitorRunResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
