# coding: utf-8

"""
    Embeddings API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.analytics_sync_request import AnalyticsSyncRequest

class TestAnalyticsSyncRequest(unittest.TestCase):
    """AnalyticsSyncRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnalyticsSyncRequest:
        """Test AnalyticsSyncRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnalyticsSyncRequest`
        """
        model = AnalyticsSyncRequest()
        if include_optional:
            return AnalyticsSyncRequest(
                account_id = 56
            )
        else:
            return AnalyticsSyncRequest(
        )
        """

    def testAnalyticsSyncRequest(self):
        """Test AnalyticsSyncRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
