# coding: utf-8

"""
    Analysis

    Analyse content using Linked Data and Knowledge Graphs.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.api.content_generation_fields_api import ContentGenerationFieldsApi


class TestContentGenerationFieldsApi(unittest.TestCase):
    """ContentGenerationFieldsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContentGenerationFieldsApi()

    def tearDown(self) -> None:
        pass

    def test_list_fields(self) -> None:
        """Test case for list_fields

        List
        """
        pass

    def test_list_fields_for_graph_ql_query(self) -> None:
        """Test case for list_fields_for_graph_ql_query

        List for GraphQl Query
        """
        pass


if __name__ == '__main__':
    unittest.main()
