# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.analyze_url_request import AnalyzeURLRequest

class TestAnalyzeURLRequest(unittest.TestCase):
    """AnalyzeURLRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnalyzeURLRequest:
        """Test AnalyzeURLRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnalyzeURLRequest`
        """
        model = AnalyzeURLRequest()
        if include_optional:
            return AnalyzeURLRequest(
                url = '0',
                num_queries = 1,
                coverage_threshold = 0
            )
        else:
            return AnalyzeURLRequest(
                url = '0',
        )
        """

    def testAnalyzeURLRequest(self):
        """Test AnalyzeURLRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
