# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.monitor_state import MonitorState

class TestMonitorState(unittest.TestCase):
    """MonitorState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonitorState(self):
        """Test MonitorState"""
        # inst = MonitorState()

if __name__ == '__main__':
    unittest.main()
