# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.api.monitor_runs_api import MonitorRunsApi


class TestMonitorRunsApi(unittest.TestCase):
    """MonitorRunsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MonitorRunsApi()

    def tearDown(self) -> None:
        pass

    def test_abort_run_accounts_account_id_monitoring_runs_run_id_delete(self) -> None:
        """Test case for abort_run_accounts_account_id_monitoring_runs_run_id_delete

        Abort Run
        """
        pass

    def test_get_run_accounts_account_id_monitoring_runs_run_id_get(self) -> None:
        """Test case for get_run_accounts_account_id_monitoring_runs_run_id_get

        Get Run
        """
        pass

    def test_list_runs_accounts_account_id_monitoring_runs_get(self) -> None:
        """Test case for list_runs_accounts_account_id_monitoring_runs_get

        List Runs
        """
        pass


if __name__ == '__main__':
    unittest.main()
