# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.models.list_segment_urls_response import ListSegmentUrlsResponse

class TestListSegmentUrlsResponse(unittest.TestCase):
    """ListSegmentUrlsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListSegmentUrlsResponse:
        """Test ListSegmentUrlsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListSegmentUrlsResponse`
        """
        model = ListSegmentUrlsResponse()
        if include_optional:
            return ListSegmentUrlsResponse(
                items = [
                    wordlift_client.models.segment_url_response.SegmentUrlResponse(
                        id = '', 
                        segment_id = '', 
                        url = '0', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total = 56,
                next_cursor = ''
            )
        else:
            return ListSegmentUrlsResponse(
                items = [
                    wordlift_client.models.segment_url_response.SegmentUrlResponse(
                        id = '', 
                        segment_id = '', 
                        url = '0', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total = 56,
        )
        """

    def testListSegmentUrlsResponse(self):
        """Test ListSegmentUrlsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
