# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.api.account_chunksets_api import AccountChunksetsApi


class TestAccountChunksetsApi(unittest.TestCase):
    """AccountChunksetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountChunksetsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_account_chunkset(self) -> None:
        """Test case for delete_account_chunkset

        Delete account chunkset
        """
        pass

    def test_get_account_chunkset(self) -> None:
        """Test case for get_account_chunkset

        Get account chunkset
        """
        pass

    def test_list_account_chunksets(self) -> None:
        """Test case for list_account_chunksets

        List account chunksets
        """
        pass

    def test_put_account_chunkset(self) -> None:
        """Test case for put_account_chunkset

        Create or replace account chunkset
        """
        pass


if __name__ == '__main__':
    unittest.main()
