# coding: utf-8

"""
    Analysis

    Analyse content using Linked Data and Knowledge Graphs.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wordlift_client.api.content_expansions_api import ContentExpansionsApi


class TestContentExpansionsApi(unittest.TestCase):
    """ContentExpansionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContentExpansionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_content_expansion(self) -> None:
        """Test case for create_content_expansion

        Create
        """
        pass


if __name__ == '__main__':
    unittest.main()
