# coding: utf-8

"""
    SEO Content Analysis API

    This API assesses the match between a URL or text content, a query, and an intent, using advanced SEO techniques.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "wordlift-client"
VERSION = "1.51.0"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "aiohttp >= 3.0.0",
    "aiohttp-retry >= 2.8.3",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="SEO Content Analysis API",
    author="WordLift",
    author_email="hello@wordlift.io",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "SEO Content Analysis API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="(c) copyright 2023-present WordLift",
    long_description_content_type='text/markdown',
    long_description="""\
    This API assesses the match between a URL or text content, a query, and an intent, using advanced SEO techniques.
    """,  # noqa: E501
    package_data={"wordlift_client": ["py.typed"]},
)
