# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CheckNameFilterValue(str, Enum):
    """
    CheckNameFilterValue
    """

    """
    allowed enum values
    """
    STRUCTURED_DATA_CHECK = 'structured_data_check'
    TITLE_CHECK = 'title_check'
    CANONICAL_CHECK = 'canonical_check'
    PAGE_META_CHECK = 'page_meta_check'
    STATUS_CHECK = 'status_check'
    PERFORMANCE_CHECK = 'performance_check'
    ROBOTS_CHECK = 'robots_check'
    RESOURCE_404_CHECK = 'resource_404_check'
    WORDLIFT_BOOTSTRAP_CHECK = 'wordlift_bootstrap_check'
    ACCOUNT_ROBOTS_CHECK = 'account_robots_check'
    AI_BOT_ACCESS_CHECK = 'ai_bot_access_check'
    ACCOUNT_LLMS_TXT_CHECK = 'account_llms_txt_check'
    ACCOUNT_SKILL_MD_CHECK = 'account_skill_md_check'
    ACCOUNT_MCP_CHECK = 'account_mcp_check'
    ACCOUNT_WEBMCP_CHECK = 'account_webmcp_check'
    OVERALL = 'overall'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CheckNameFilterValue from a JSON string"""
        return cls(json.loads(json_str))


