# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CrawlPageStatus(str, Enum):
    """
    CrawlPageStatus
    """

    """
    allowed enum values
    """
    OK = 'ok'
    FAILED = 'failed'
    ALL = 'all'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CrawlPageStatus from a JSON string"""
        return cls(json.loads(json_str))


