# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class JsRendering(BaseModel):
    """
    JsRendering
    """ # noqa: E501
    status: Optional[StrictStr] = None
    explanation: Optional[StrictStr] = None
    framework_detected: Optional[StrictStr] = Field(default=None, description="Detected JavaScript framework (React, Vue, Angular, etc.)", alias="frameworkDetected")
    rendering_type: Optional[StrictStr] = Field(default=None, description="Type of rendering used by the site", alias="renderingType")
    ai_accessibility: Optional[StrictStr] = Field(default=None, description="How accessible the content is to AI agents", alias="aiAccessibility")
    content_availability: Optional[StrictStr] = Field(default=None, description="Description of content availability in HTML", alias="contentAvailability")
    recommendations: Optional[List[StrictStr]] = Field(default=None, description="Recommendations for improving JS rendering")
    __properties: ClassVar[List[str]] = ["status", "explanation", "frameworkDetected", "renderingType", "aiAccessibility", "contentAvailability", "recommendations"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Good', 'Needs Improvement', 'Poor']):
            raise ValueError("must be one of enum values ('Good', 'Needs Improvement', 'Poor')")
        return value

    @field_validator('rendering_type')
    def rendering_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Static', 'SSR', 'SSG', 'CSR', 'Hybrid']):
            raise ValueError("must be one of enum values ('Static', 'SSR', 'SSG', 'CSR', 'Hybrid')")
        return value

    @field_validator('ai_accessibility')
    def ai_accessibility_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Excellent', 'Good', 'Limited', 'Blocked']):
            raise ValueError("must be one of enum values ('Excellent', 'Good', 'Limited', 'Blocked')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JsRendering from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JsRendering from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "explanation": obj.get("explanation"),
            "frameworkDetected": obj.get("frameworkDetected"),
            "renderingType": obj.get("renderingType"),
            "aiAccessibility": obj.get("aiAccessibility"),
            "contentAvailability": obj.get("contentAvailability"),
            "recommendations": obj.get("recommendations")
        })
        return _obj


