# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MonitorCheckName(str, Enum):
    """
    Identifier of a monitor check plugin.  Mirrors the ``name`` returned by SDK monitor plugins and the ``check_name`` column on ``monitor_check_results``. Listed here for type-safety on the domain and API models that reference a check. Each value imports its string from the plugin package that owns it, so writer (this enum) and reader (the plugin's ``Monitor.name``) can't drift.
    """

    """
    allowed enum values
    """
    STRUCTURED_DATA_CHECK = 'structured_data_check'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MonitorCheckName from a JSON string"""
        return cls(json.loads(json_str))


