# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from wordlift_client.models.question_and_answer import QuestionAndAnswer
from typing import Optional, Set
from typing_extensions import Self

class QuestionAndAnswerSet(BaseModel):
    """
    Generated Q&A content.
    """ # noqa: E501
    created_entity_gaps: Optional[List[StrictStr]] = Field(default=None, description="Entity Gaps created for the Web Page.")
    id: Optional[StrictStr] = Field(default=None, description="The unique id.")
    is_smart_content_of: Optional[StrictStr] = Field(default=None, description="The Web Page this smart content is created for.")
    published: Optional[StrictBool] = Field(default=None, description="The published status of the smart content.")
    questions_and_answers: Optional[List[QuestionAndAnswer]] = Field(default=None, description="The generated questions and answers.")
    selected_entity_gaps: Optional[List[StrictStr]] = Field(default=None, description="Entity Gaps used to generate the Smart Content.")
    smart_content_project_id: Optional[StrictInt] = None
    url: Optional[StrictStr] = Field(default=None, description="The URL of the Web Page this smart content is created for.")
    __properties: ClassVar[List[str]] = ["created_entity_gaps", "id", "is_smart_content_of", "published", "questions_and_answers", "selected_entity_gaps", "smart_content_project_id", "url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QuestionAndAnswerSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "published",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in questions_and_answers (list)
        _items = []
        if self.questions_and_answers:
            for _item in self.questions_and_answers:
                if _item:
                    _items.append(_item.to_dict())
            _dict['questions_and_answers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QuestionAndAnswerSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_entity_gaps": obj.get("created_entity_gaps"),
            "id": obj.get("id"),
            "is_smart_content_of": obj.get("is_smart_content_of"),
            "published": obj.get("published"),
            "questions_and_answers": [QuestionAndAnswer.from_dict(_item) for _item in obj["questions_and_answers"]] if obj.get("questions_and_answers") is not None else None,
            "selected_entity_gaps": obj.get("selected_entity_gaps"),
            "smart_content_project_id": obj.get("smart_content_project_id"),
            "url": obj.get("url")
        })
        return _obj


