# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from wordlift_client.models.resources_agent_skills_index import ResourcesAgentSkillsIndex
from wordlift_client.models.resources_llms_txt import ResourcesLlmsTxt
from wordlift_client.models.resources_mcp_json import ResourcesMcpJson
from wordlift_client.models.resources_mcp_link_tag import ResourcesMcpLinkTag
from wordlift_client.models.resources_mcp_server_card import ResourcesMcpServerCard
from wordlift_client.models.resources_robots_txt import ResourcesRobotsTxt
from wordlift_client.models.resources_skill_md import ResourcesSkillMd
from wordlift_client.models.resources_webmcp_tools_json import ResourcesWebmcpToolsJson
from typing import Optional, Set
from typing_extensions import Self

class Resources(BaseModel):
    """
    What the audit fetched or detected, one entry per resource. Supersedes the file facts in siteFiles
    """ # noqa: E501
    robots_txt: ResourcesRobotsTxt = Field(alias="robotsTxt")
    llms_txt: ResourcesLlmsTxt = Field(alias="llmsTxt")
    skill_md: ResourcesSkillMd = Field(alias="skillMd")
    mcp_json: ResourcesMcpJson = Field(alias="mcpJson")
    mcp_server_card: ResourcesMcpServerCard = Field(alias="mcpServerCard")
    webmcp_tools_json: ResourcesWebmcpToolsJson = Field(alias="webmcpToolsJson")
    agent_skills_index: ResourcesAgentSkillsIndex = Field(alias="agentSkillsIndex")
    mcp_link_tag: ResourcesMcpLinkTag = Field(alias="mcpLinkTag")
    __properties: ClassVar[List[str]] = ["robotsTxt", "llmsTxt", "skillMd", "mcpJson", "mcpServerCard", "webmcpToolsJson", "agentSkillsIndex", "mcpLinkTag"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Resources from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of robots_txt
        if self.robots_txt:
            _dict['robotsTxt'] = self.robots_txt.to_dict()
        # override the default output from pydantic by calling `to_dict()` of llms_txt
        if self.llms_txt:
            _dict['llmsTxt'] = self.llms_txt.to_dict()
        # override the default output from pydantic by calling `to_dict()` of skill_md
        if self.skill_md:
            _dict['skillMd'] = self.skill_md.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mcp_json
        if self.mcp_json:
            _dict['mcpJson'] = self.mcp_json.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mcp_server_card
        if self.mcp_server_card:
            _dict['mcpServerCard'] = self.mcp_server_card.to_dict()
        # override the default output from pydantic by calling `to_dict()` of webmcp_tools_json
        if self.webmcp_tools_json:
            _dict['webmcpToolsJson'] = self.webmcp_tools_json.to_dict()
        # override the default output from pydantic by calling `to_dict()` of agent_skills_index
        if self.agent_skills_index:
            _dict['agentSkillsIndex'] = self.agent_skills_index.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mcp_link_tag
        if self.mcp_link_tag:
            _dict['mcpLinkTag'] = self.mcp_link_tag.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Resources from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "robotsTxt": ResourcesRobotsTxt.from_dict(obj["robotsTxt"]) if obj.get("robotsTxt") is not None else None,
            "llmsTxt": ResourcesLlmsTxt.from_dict(obj["llmsTxt"]) if obj.get("llmsTxt") is not None else None,
            "skillMd": ResourcesSkillMd.from_dict(obj["skillMd"]) if obj.get("skillMd") is not None else None,
            "mcpJson": ResourcesMcpJson.from_dict(obj["mcpJson"]) if obj.get("mcpJson") is not None else None,
            "mcpServerCard": ResourcesMcpServerCard.from_dict(obj["mcpServerCard"]) if obj.get("mcpServerCard") is not None else None,
            "webmcpToolsJson": ResourcesWebmcpToolsJson.from_dict(obj["webmcpToolsJson"]) if obj.get("webmcpToolsJson") is not None else None,
            "agentSkillsIndex": ResourcesAgentSkillsIndex.from_dict(obj["agentSkillsIndex"]) if obj.get("agentSkillsIndex") is not None else None,
            "mcpLinkTag": ResourcesMcpLinkTag.from_dict(obj["mcpLinkTag"]) if obj.get("mcpLinkTag") is not None else None
        })
        return _obj


