# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from wordlift_client.models.inline_dataset import InlineDataset
from wordlift_client.models.resolve_mention import ResolveMention
from typing import Optional, Set
from typing_extensions import Self

class ResolveRequest(BaseModel):
    """
    ResolveRequest
    """ # noqa: E501
    text: Annotated[str, Field(min_length=1, strict=True, max_length=100000)]
    dataset_uri: Optional[StrictStr] = Field(default='wikidata://public', description="The world to resolve against: `wikidata://public` (default), `wordlift://dataset/me` (your WordLift graph, read with your key), `inline` (with `dataset`), or a comma-separated ordered list such as `wordlift://dataset/me,wikidata://public` (your entities first, Wikidata for the rest).")
    language: Optional[StrictStr] = None
    mentions: Optional[List[ResolveMention]] = None
    include: Optional[List[StrictStr]] = Field(default=None, description="Diagnostics: candidates, evidence")
    confidence: Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = Field(default=0.5, description="NER threshold when the engine detects mentions")
    dataset: Optional[InlineDataset] = None
    __properties: ClassVar[List[str]] = ["text", "dataset_uri", "language", "mentions", "include", "confidence", "dataset"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResolveRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in mentions (list)
        _items = []
        if self.mentions:
            for _item in self.mentions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['mentions'] = _items
        # override the default output from pydantic by calling `to_dict()` of dataset
        if self.dataset:
            _dict['dataset'] = self.dataset.to_dict()
        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['language'] = None

        # set to None if mentions (nullable) is None
        # and model_fields_set contains the field
        if self.mentions is None and "mentions" in self.model_fields_set:
            _dict['mentions'] = None

        # set to None if dataset (nullable) is None
        # and model_fields_set contains the field
        if self.dataset is None and "dataset" in self.model_fields_set:
            _dict['dataset'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResolveRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "text": obj.get("text"),
            "dataset_uri": obj.get("dataset_uri") if obj.get("dataset_uri") is not None else 'wikidata://public',
            "language": obj.get("language"),
            "mentions": [ResolveMention.from_dict(_item) for _item in obj["mentions"]] if obj.get("mentions") is not None else None,
            "include": obj.get("include"),
            "confidence": obj.get("confidence") if obj.get("confidence") is not None else 0.5,
            "dataset": InlineDataset.from_dict(obj["dataset"]) if obj.get("dataset") is not None else None
        })
        return _obj


