# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from wordlift_client.models.detected_schema import DetectedSchema
from wordlift_client.models.schema_recommendation import SchemaRecommendation
from typing import Optional, Set
from typing_extensions import Self

class StructuredData(BaseModel):
    """
    StructuredData
    """ # noqa: E501
    score: Optional[Annotated[int, Field(le=15, strict=True, ge=0)]] = Field(default=None, description="Numeric score for structured data (0-15)")
    status: Optional[StrictStr] = None
    explanation: Optional[StrictStr] = None
    has_schema: Optional[StrictBool] = Field(default=None, description="Whether schema.org markup is present", alias="hasSchema")
    has_json_ld: Optional[StrictBool] = Field(default=None, description="Whether JSON-LD structured data is present", alias="hasJsonLd")
    has_microdata: Optional[StrictBool] = Field(default=None, description="Whether Microdata structured data is present", alias="hasMicrodata")
    detected_schemas: Optional[List[DetectedSchema]] = Field(default=None, description="List of detected schema types with their formats", alias="detectedSchemas")
    recommendations: Optional[List[SchemaRecommendation]] = Field(default=None, description="Recommendations for improving structured data")
    __properties: ClassVar[List[str]] = ["score", "status", "explanation", "hasSchema", "hasJsonLd", "hasMicrodata", "detectedSchemas", "recommendations"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Good', 'Needs Improvement', 'Poor', 'Unknown']):
            raise ValueError("must be one of enum values ('Good', 'Needs Improvement', 'Poor', 'Unknown')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StructuredData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in detected_schemas (list)
        _items = []
        if self.detected_schemas:
            for _item in self.detected_schemas:
                if _item:
                    _items.append(_item.to_dict())
            _dict['detectedSchemas'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in recommendations (list)
        _items = []
        if self.recommendations:
            for _item in self.recommendations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['recommendations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StructuredData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "score": obj.get("score"),
            "status": obj.get("status"),
            "explanation": obj.get("explanation"),
            "hasSchema": obj.get("hasSchema"),
            "hasJsonLd": obj.get("hasJsonLd"),
            "hasMicrodata": obj.get("hasMicrodata"),
            "detectedSchemas": [DetectedSchema.from_dict(_item) for _item in obj["detectedSchemas"]] if obj.get("detectedSchemas") is not None else None,
            "recommendations": [SchemaRecommendation.from_dict(_item) for _item in obj["recommendations"]] if obj.get("recommendations") is not None else None
        })
        return _obj


