# coding: utf-8

"""
    WordLift API

    WordLift API

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import datetime
from pydantic import Field, StrictStr
from typing import List, Optional, Union
from typing_extensions import Annotated
from wordlift_client.models.check_timeseries_response import CheckTimeseriesResponse
from wordlift_client.models.list_monitor_status_response import ListMonitorStatusResponse
from wordlift_client.models.monitor_status_check_status import MonitorStatusCheckStatus
from wordlift_client.models.monitor_status_order_by import MonitorStatusOrderBy
from wordlift_client.models.monitor_status_response import MonitorStatusResponse
from wordlift_client.models.sort_direction import SortDirection

from wordlift_client.api_client import ApiClient, RequestSerialized
from wordlift_client.api_response import ApiResponse
from wordlift_client.rest import RESTResponseType


class MonitorStatusApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    async def get_check_timeseries_accounts_account_id_monitoring_monitors_monitor_id_checks_check_name_get(
        self,
        monitor_id: StrictStr,
        check_name: StrictStr,
        account_id: StrictStr,
        since: Annotated[Optional[datetime], Field(description="Return results on or after this RFC 3339 timestamp (inclusive).")] = None,
        to: Annotated[Optional[datetime], Field(description="Return results on or before this RFC 3339 timestamp (inclusive).")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]], Field(description="Maximum number of data points to return.")] = None,
        sort: Annotated[Optional[SortDirection], Field(description="Sort order: 'asc' for oldest-first (graphs), 'desc' for newest-first (history).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CheckTimeseriesResponse:
        """Get Check Timeseries


        :param monitor_id: (required)
        :type monitor_id: str
        :param check_name: (required)
        :type check_name: str
        :param account_id: (required)
        :type account_id: str
        :param since: Return results on or after this RFC 3339 timestamp (inclusive).
        :type since: datetime
        :param to: Return results on or before this RFC 3339 timestamp (inclusive).
        :type to: datetime
        :param limit: Maximum number of data points to return.
        :type limit: int
        :param sort: Sort order: 'asc' for oldest-first (graphs), 'desc' for newest-first (history).
        :type sort: SortDirection
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_check_timeseries_accounts_account_id_monitoring_monitors_monitor_id_checks_check_name_get_serialize(
            monitor_id=monitor_id,
            check_name=check_name,
            account_id=account_id,
            since=since,
            to=to,
            limit=limit,
            sort=sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CheckTimeseriesResponse",
            '422': "MonitorHTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def get_check_timeseries_accounts_account_id_monitoring_monitors_monitor_id_checks_check_name_get_with_http_info(
        self,
        monitor_id: StrictStr,
        check_name: StrictStr,
        account_id: StrictStr,
        since: Annotated[Optional[datetime], Field(description="Return results on or after this RFC 3339 timestamp (inclusive).")] = None,
        to: Annotated[Optional[datetime], Field(description="Return results on or before this RFC 3339 timestamp (inclusive).")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]], Field(description="Maximum number of data points to return.")] = None,
        sort: Annotated[Optional[SortDirection], Field(description="Sort order: 'asc' for oldest-first (graphs), 'desc' for newest-first (history).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CheckTimeseriesResponse]:
        """Get Check Timeseries


        :param monitor_id: (required)
        :type monitor_id: str
        :param check_name: (required)
        :type check_name: str
        :param account_id: (required)
        :type account_id: str
        :param since: Return results on or after this RFC 3339 timestamp (inclusive).
        :type since: datetime
        :param to: Return results on or before this RFC 3339 timestamp (inclusive).
        :type to: datetime
        :param limit: Maximum number of data points to return.
        :type limit: int
        :param sort: Sort order: 'asc' for oldest-first (graphs), 'desc' for newest-first (history).
        :type sort: SortDirection
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_check_timeseries_accounts_account_id_monitoring_monitors_monitor_id_checks_check_name_get_serialize(
            monitor_id=monitor_id,
            check_name=check_name,
            account_id=account_id,
            since=since,
            to=to,
            limit=limit,
            sort=sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CheckTimeseriesResponse",
            '422': "MonitorHTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def get_check_timeseries_accounts_account_id_monitoring_monitors_monitor_id_checks_check_name_get_without_preload_content(
        self,
        monitor_id: StrictStr,
        check_name: StrictStr,
        account_id: StrictStr,
        since: Annotated[Optional[datetime], Field(description="Return results on or after this RFC 3339 timestamp (inclusive).")] = None,
        to: Annotated[Optional[datetime], Field(description="Return results on or before this RFC 3339 timestamp (inclusive).")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]], Field(description="Maximum number of data points to return.")] = None,
        sort: Annotated[Optional[SortDirection], Field(description="Sort order: 'asc' for oldest-first (graphs), 'desc' for newest-first (history).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Check Timeseries


        :param monitor_id: (required)
        :type monitor_id: str
        :param check_name: (required)
        :type check_name: str
        :param account_id: (required)
        :type account_id: str
        :param since: Return results on or after this RFC 3339 timestamp (inclusive).
        :type since: datetime
        :param to: Return results on or before this RFC 3339 timestamp (inclusive).
        :type to: datetime
        :param limit: Maximum number of data points to return.
        :type limit: int
        :param sort: Sort order: 'asc' for oldest-first (graphs), 'desc' for newest-first (history).
        :type sort: SortDirection
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_check_timeseries_accounts_account_id_monitoring_monitors_monitor_id_checks_check_name_get_serialize(
            monitor_id=monitor_id,
            check_name=check_name,
            account_id=account_id,
            since=since,
            to=to,
            limit=limit,
            sort=sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CheckTimeseriesResponse",
            '422': "MonitorHTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_check_timeseries_accounts_account_id_monitoring_monitors_monitor_id_checks_check_name_get_serialize(
        self,
        monitor_id,
        check_name,
        account_id,
        since,
        to,
        limit,
        sort,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if monitor_id is not None:
            _path_params['monitor_id'] = monitor_id
        if check_name is not None:
            _path_params['check_name'] = check_name
        if account_id is not None:
            _path_params['account_id'] = account_id
        # process the query parameters
        if since is not None:
            if isinstance(since, datetime):
                _query_params.append(
                    (
                        'since',
                        since.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('since', since))
            
        if to is not None:
            if isinstance(to, datetime):
                _query_params.append(
                    (
                        'to',
                        to.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('to', to))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if sort is not None:
            
            _query_params.append(('sort', sort.value))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKey'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/accounts/{account_id}/monitoring/monitors/{monitor_id}/checks/{check_name}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def get_monitor_status_accounts_account_id_monitoring_monitors_monitor_id_status_get(
        self,
        monitor_id: StrictStr,
        account_id: StrictStr,
        segment_id: Annotated[Optional[StrictStr], Field(description="Return the monitor's status scoped to this segment instead of the aggregate view. Omitted or empty returns the aggregate view.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> MonitorStatusResponse:
        """Get Monitor Status


        :param monitor_id: (required)
        :type monitor_id: str
        :param account_id: (required)
        :type account_id: str
        :param segment_id: Return the monitor's status scoped to this segment instead of the aggregate view. Omitted or empty returns the aggregate view.
        :type segment_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_monitor_status_accounts_account_id_monitoring_monitors_monitor_id_status_get_serialize(
            monitor_id=monitor_id,
            account_id=account_id,
            segment_id=segment_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MonitorStatusResponse",
            '422': "MonitorHTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def get_monitor_status_accounts_account_id_monitoring_monitors_monitor_id_status_get_with_http_info(
        self,
        monitor_id: StrictStr,
        account_id: StrictStr,
        segment_id: Annotated[Optional[StrictStr], Field(description="Return the monitor's status scoped to this segment instead of the aggregate view. Omitted or empty returns the aggregate view.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[MonitorStatusResponse]:
        """Get Monitor Status


        :param monitor_id: (required)
        :type monitor_id: str
        :param account_id: (required)
        :type account_id: str
        :param segment_id: Return the monitor's status scoped to this segment instead of the aggregate view. Omitted or empty returns the aggregate view.
        :type segment_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_monitor_status_accounts_account_id_monitoring_monitors_monitor_id_status_get_serialize(
            monitor_id=monitor_id,
            account_id=account_id,
            segment_id=segment_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MonitorStatusResponse",
            '422': "MonitorHTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def get_monitor_status_accounts_account_id_monitoring_monitors_monitor_id_status_get_without_preload_content(
        self,
        monitor_id: StrictStr,
        account_id: StrictStr,
        segment_id: Annotated[Optional[StrictStr], Field(description="Return the monitor's status scoped to this segment instead of the aggregate view. Omitted or empty returns the aggregate view.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Monitor Status


        :param monitor_id: (required)
        :type monitor_id: str
        :param account_id: (required)
        :type account_id: str
        :param segment_id: Return the monitor's status scoped to this segment instead of the aggregate view. Omitted or empty returns the aggregate view.
        :type segment_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_monitor_status_accounts_account_id_monitoring_monitors_monitor_id_status_get_serialize(
            monitor_id=monitor_id,
            account_id=account_id,
            segment_id=segment_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MonitorStatusResponse",
            '422': "MonitorHTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_monitor_status_accounts_account_id_monitoring_monitors_monitor_id_status_get_serialize(
        self,
        monitor_id,
        account_id,
        segment_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if monitor_id is not None:
            _path_params['monitor_id'] = monitor_id
        if account_id is not None:
            _path_params['account_id'] = account_id
        # process the query parameters
        if segment_id is not None:
            
            _query_params.append(('segment_id', segment_id))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKey'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/accounts/{account_id}/monitoring/monitors/{monitor_id}/status',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def list_monitor_statuses_accounts_account_id_monitoring_status_get(
        self,
        account_id: StrictStr,
        url: Annotated[Optional[StrictStr], Field(description="Glob pattern to filter by URL (e.g. `*example.com*`).")] = None,
        status: Annotated[Optional[List[MonitorStatusCheckStatus]], Field(description="Filter by check status (repeatable, e.g. `?status=ERROR&status=WARNING`).")] = None,
        score_min: Annotated[Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]], Field(description="Minimum score (inclusive).")] = None,
        score_max: Annotated[Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]], Field(description="Maximum score (inclusive).")] = None,
        segment_id: Annotated[Optional[StrictStr], Field(description="Return only monitor statuses matched by the given segment's matchers. Pass 'unassigned' to match monitor statuses matched by no segment. Omitted or empty returns the aggregate (unscoped) view.")] = None,
        order_by: Annotated[Optional[MonitorStatusOrderBy], Field(description="Field to sort by.")] = None,
        sort: Annotated[Optional[SortDirection], Field(description="Sort direction.")] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Opaque pagination cursor from a previous response.")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=50, strict=True, ge=1)]], Field(description="Maximum number of items to return.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ListMonitorStatusResponse:
        """List Monitor Statuses


        :param account_id: (required)
        :type account_id: str
        :param url: Glob pattern to filter by URL (e.g. `*example.com*`).
        :type url: str
        :param status: Filter by check status (repeatable, e.g. `?status=ERROR&status=WARNING`).
        :type status: List[MonitorStatusCheckStatus]
        :param score_min: Minimum score (inclusive).
        :type score_min: float
        :param score_max: Maximum score (inclusive).
        :type score_max: float
        :param segment_id: Return only monitor statuses matched by the given segment's matchers. Pass 'unassigned' to match monitor statuses matched by no segment. Omitted or empty returns the aggregate (unscoped) view.
        :type segment_id: str
        :param order_by: Field to sort by.
        :type order_by: MonitorStatusOrderBy
        :param sort: Sort direction.
        :type sort: SortDirection
        :param cursor: Opaque pagination cursor from a previous response.
        :type cursor: str
        :param limit: Maximum number of items to return.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_monitor_statuses_accounts_account_id_monitoring_status_get_serialize(
            account_id=account_id,
            url=url,
            status=status,
            score_min=score_min,
            score_max=score_max,
            segment_id=segment_id,
            order_by=order_by,
            sort=sort,
            cursor=cursor,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListMonitorStatusResponse",
            '422': "MonitorHTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def list_monitor_statuses_accounts_account_id_monitoring_status_get_with_http_info(
        self,
        account_id: StrictStr,
        url: Annotated[Optional[StrictStr], Field(description="Glob pattern to filter by URL (e.g. `*example.com*`).")] = None,
        status: Annotated[Optional[List[MonitorStatusCheckStatus]], Field(description="Filter by check status (repeatable, e.g. `?status=ERROR&status=WARNING`).")] = None,
        score_min: Annotated[Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]], Field(description="Minimum score (inclusive).")] = None,
        score_max: Annotated[Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]], Field(description="Maximum score (inclusive).")] = None,
        segment_id: Annotated[Optional[StrictStr], Field(description="Return only monitor statuses matched by the given segment's matchers. Pass 'unassigned' to match monitor statuses matched by no segment. Omitted or empty returns the aggregate (unscoped) view.")] = None,
        order_by: Annotated[Optional[MonitorStatusOrderBy], Field(description="Field to sort by.")] = None,
        sort: Annotated[Optional[SortDirection], Field(description="Sort direction.")] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Opaque pagination cursor from a previous response.")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=50, strict=True, ge=1)]], Field(description="Maximum number of items to return.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ListMonitorStatusResponse]:
        """List Monitor Statuses


        :param account_id: (required)
        :type account_id: str
        :param url: Glob pattern to filter by URL (e.g. `*example.com*`).
        :type url: str
        :param status: Filter by check status (repeatable, e.g. `?status=ERROR&status=WARNING`).
        :type status: List[MonitorStatusCheckStatus]
        :param score_min: Minimum score (inclusive).
        :type score_min: float
        :param score_max: Maximum score (inclusive).
        :type score_max: float
        :param segment_id: Return only monitor statuses matched by the given segment's matchers. Pass 'unassigned' to match monitor statuses matched by no segment. Omitted or empty returns the aggregate (unscoped) view.
        :type segment_id: str
        :param order_by: Field to sort by.
        :type order_by: MonitorStatusOrderBy
        :param sort: Sort direction.
        :type sort: SortDirection
        :param cursor: Opaque pagination cursor from a previous response.
        :type cursor: str
        :param limit: Maximum number of items to return.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_monitor_statuses_accounts_account_id_monitoring_status_get_serialize(
            account_id=account_id,
            url=url,
            status=status,
            score_min=score_min,
            score_max=score_max,
            segment_id=segment_id,
            order_by=order_by,
            sort=sort,
            cursor=cursor,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListMonitorStatusResponse",
            '422': "MonitorHTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def list_monitor_statuses_accounts_account_id_monitoring_status_get_without_preload_content(
        self,
        account_id: StrictStr,
        url: Annotated[Optional[StrictStr], Field(description="Glob pattern to filter by URL (e.g. `*example.com*`).")] = None,
        status: Annotated[Optional[List[MonitorStatusCheckStatus]], Field(description="Filter by check status (repeatable, e.g. `?status=ERROR&status=WARNING`).")] = None,
        score_min: Annotated[Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]], Field(description="Minimum score (inclusive).")] = None,
        score_max: Annotated[Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]], Field(description="Maximum score (inclusive).")] = None,
        segment_id: Annotated[Optional[StrictStr], Field(description="Return only monitor statuses matched by the given segment's matchers. Pass 'unassigned' to match monitor statuses matched by no segment. Omitted or empty returns the aggregate (unscoped) view.")] = None,
        order_by: Annotated[Optional[MonitorStatusOrderBy], Field(description="Field to sort by.")] = None,
        sort: Annotated[Optional[SortDirection], Field(description="Sort direction.")] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Opaque pagination cursor from a previous response.")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=50, strict=True, ge=1)]], Field(description="Maximum number of items to return.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List Monitor Statuses


        :param account_id: (required)
        :type account_id: str
        :param url: Glob pattern to filter by URL (e.g. `*example.com*`).
        :type url: str
        :param status: Filter by check status (repeatable, e.g. `?status=ERROR&status=WARNING`).
        :type status: List[MonitorStatusCheckStatus]
        :param score_min: Minimum score (inclusive).
        :type score_min: float
        :param score_max: Maximum score (inclusive).
        :type score_max: float
        :param segment_id: Return only monitor statuses matched by the given segment's matchers. Pass 'unassigned' to match monitor statuses matched by no segment. Omitted or empty returns the aggregate (unscoped) view.
        :type segment_id: str
        :param order_by: Field to sort by.
        :type order_by: MonitorStatusOrderBy
        :param sort: Sort direction.
        :type sort: SortDirection
        :param cursor: Opaque pagination cursor from a previous response.
        :type cursor: str
        :param limit: Maximum number of items to return.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_monitor_statuses_accounts_account_id_monitoring_status_get_serialize(
            account_id=account_id,
            url=url,
            status=status,
            score_min=score_min,
            score_max=score_max,
            segment_id=segment_id,
            order_by=order_by,
            sort=sort,
            cursor=cursor,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListMonitorStatusResponse",
            '422': "MonitorHTTPValidationError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_monitor_statuses_accounts_account_id_monitoring_status_get_serialize(
        self,
        account_id,
        url,
        status,
        score_min,
        score_max,
        segment_id,
        order_by,
        sort,
        cursor,
        limit,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'status': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if account_id is not None:
            _path_params['account_id'] = account_id
        # process the query parameters
        if url is not None:
            
            _query_params.append(('url', url))
            
        if status is not None:
            
            _query_params.append(('status', status))
            
        if score_min is not None:
            
            _query_params.append(('score_min', score_min))
            
        if score_max is not None:
            
            _query_params.append(('score_max', score_max))
            
        if segment_id is not None:
            
            _query_params.append(('segment_id', segment_id))
            
        if order_by is not None:
            
            _query_params.append(('order_by', order_by.value))
            
        if sort is not None:
            
            _query_params.append(('sort', sort.value))
            
        if cursor is not None:
            
            _query_params.append(('cursor', cursor))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKey'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/accounts/{account_id}/monitoring/status',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


