info:
  contact:
    email: hello@wordlift.io
    name: WordLift
    url: https://wordlift.io
  description: WordLift API
  license:
    name: (c) copyright 2022-present WordLift
    url: https://wordlift.io
  termsOfService: https://wordlift.io/terms-of-service/
  title: WordLift API
  version: "1.0"
components:
  securitySchemes:
    ApiKey:
      description: "`Key {your key}`"
      in: header
      name: Authorization
      type: apiKey
    BasicAuth:
      description: "`Basic {encoded username:password}`"
      in: header
      name: Authorization
      scheme: basic
      type: http
    OAuth2:
      flows:
        authorizationCode:
          authorizationUrl: https://s.wordlift.io/oauth/authorize/
          scopes:
            basic: basic scope
          tokenUrl: https://s.wordlift.io/oauth/token/
      type: oauth2
servers:
  - url: https://api.wordlift.io
