openapi: 3.1.0
info:
  title: WordLift Image-to-Text API
  description: API for converting images into text descriptions using AI technology.
  version: 1.0.0
paths:
  /image-2-text-v1:
    post:
      tags:
        - Image-to-Text
      summary: Convert Image to Text
      description: Process an image and generate descriptive text based on its content.
      operationId: image_to_text_api_image_2_text_v1_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ImageToTextRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageToTextResponse"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
      security:
        - ApiKey: []
components:
  schemas:
    ImageToTextRequest:
      properties:
        image_url:
          type: string
          title: Image URL
          description: URL of the image to be processed
        prompt_type:
          type: string
          title: Prompt Type
          description: Type of analysis to perform
          enum: ["Other", "Product", "Scene"]
        custom_prompt:
          type: string
          title: Custom Prompt
          description: Custom instructions for text generation
      type: object
      required:
        - image_url
        - prompt_type
      title: ImageToTextRequest
    ImageToTextResponse:
      properties:
        text:
          type: string
          title: Text
          description: Generated text description of the image
      type: object
      required:
        - text
      title: ImageToTextResponse
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: authorization
servers:
  - url: https://api.wordlift.io
    description: WordLift Image-to-Text API
