openapi: 3.0.1
info:
  title: SEO Content Analysis API
  version: "1.0"
  description: This API assesses the match between a URL or text content, a query, and an intent, using advanced SEO techniques.
  termsOfService: https://wordlift.io/terms-of-service/
  contact:
    name: WordLift
    url: https://wordlift.io
    email: hello@wordlift.io
  license:
    name: (c) copyright 2023-present WordLift
    url: https://wordlift.io
servers:
  - url: https://api.wordlift.io/quality-rating

tags:
  - name: SEO Scores
    description: Create a SEO Score

paths:
  /score:
    post:
      tags:
        - SEO Scores
      summary: Create
      operationId: createSEOScore
      requestBody:
        description: body
        required: true
        content:
          application/json:
            schema:
              type: object
              # oneOf:
              #   - required: [url]
              #   - required: [text]
              properties:
                url:
                  type: string
                  description: URL of the content to be analyzed. Mutually exclusive with text.
                text:
                  type: string
                  description: A paragraph of text content to be analyzed. Mutually exclusive with URL.
                keyword:
                  type: string
                  description: Keyword or query related to the content.
                description_narrative:
                  type: string
                  description: Narrative description of the intent behind the query.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  analyze:
                    type: string
                    example: '[{"M": 2, "T": 2, "O": 2}]'
                    description: Traffic light system indicating the match. M for match, T for trustworthiness, O for overall score.
        '400':
          description: Bad request
          content: { }
        '401':
          description: Unauthorized
          content: { }
        '500':
          description: Internal server error
          content: { }
      security:
        - ApiKey: []

components:
  securitySchemes:
    ApiKey:
      type: apiKey
      name: Authorization
      in: header
