openapi: 3.0.1
info:
  title: WordLift Sitemap Generator API
  description: Generate a sitemap from a GraphQL query to WordLift KG.
  termsOfService: https://wordlift.io/terms-of-service/
  contact:
    name: WordLift
    url: https://wordlift.io
    email: hello@wordlift.io
  license:
    name: (c) copyright 2023-present WordLift
    url: https://wordlift.io
  version: "1.0"
servers:
- url: https://wl-sitemap-generator.azurewebsites.net
tags:
- name: Sitemap Generator
  description: Generate sitemaps using GraphQL queries to WordLift KG.
paths:
  /build:
    post:
      tags:
      - Sitemap Generator
      summary: Generate Sitemap
      description: |
        Generates a sitemap from a GraphQL query to WordLift KG. You must provide a valid GraphQL query as the request body.
      operationId: generateSitemap
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  example: "{ foodEstablishments { name: string(name: \"schema:name\") url: string(name: \"schema:url\") }}"
                operationName:
                  type: string
                  example: "Operations"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  sitemap:
                    type: string
                    description: The generated sitemap in XML format.
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      security:
        - ApiKey: []
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: Authorization
